//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MDI.rc
//
#define IDD_ABOUTBOX                    100
#define IDM_BLACK                       101
#define IDM_WHITE                       102
#define IDM_RED                         103
#define IDM_BLUE                        104
#define IDM_GREEN                       105
#define IDR_MAINFRAME                   128
#define IDR_MDITYPE                     129
#define IDR_MDITEXT                     129
#define IDI_MDITEXT                     130
#define IDC_MDITEXT                     131
#define ID_FILE_TEXT                    32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
