//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Template.rc
//
#define IDD_TEMPLATE_DIALOG             102
#define IDD_TEMPLATE                    102
#define IDR_MAINFRAME                   128
#define IDC_STATICTEXT                  1000
#define IDC_EDITTEXT                    1001
#define IDC_XPOS                        1003
#define IDC_YPOS                        1004
#define IDC_WIDTH                       1005
#define IDC_HEIGHT                      1006
#define IDC_TITLE                       1007
#define ID_SHOW                         1008
#define IDC_CAPTION                     1009
#define IDC_TEXTSTATIC                  1010
#define IDC_TEXTEDIT                    1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
