//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DlgSmpl.rc
//
#define IDD_ABOUTBOX                    100
#define IDM_BLACK                       101
#define IDM_RED                         102
#define IDM_BLUE                        103
#define IDM_GREEN                       104
#define IDM_WHITE                       105
#define IDM_CUSTOM                      106
#define IDR_MAINFRAME                   128
#define IDR_DLGSMPTYPE                  129
#define IDR_CHILD                       129
#define ID_NEW                          32771
#define ID_OPEN                         32772
#define ID_CLOSE                        32782
#define IDM_FONT                        32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
