//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CtrlBars.rc
//
#define IDB_TOOLBAR                     3
#define IDD_ABOUTBOX                    100
#define IDC_PANE                     101
#define IDW_COMBO                       102
#define IDD_VIEWSELECT                  102
#define ID_INDICATOR_TIME               104
#define ID_INDICATOR_IDLE               105
#define IDB_PANE                     106
#define IDR_MAINFRAME                   128
#define IDW_TOOLBAR                     501
#define IDM_VIEWPANE                 502
#define ID_PANEERASE                 601
#define ID_PANEPEN                   602
#define ID_PANESELECT                603
#define ID_PANEBRUSH                 604
#define ID_PANESPRAY                 605
#define ID_PANEPAINT                 606
#define ID_PANELINE                  607
#define ID_PANEEYEDROP               608
#define ID_PANEMAG                   609
#define ID_PANERECT                  610
#define ID_PANEROUND                 611
#define ID_PANEOVAL                  612
#define IDM_PANE_2COLUMN             32804
#define IDM_PANE_3COLUMN             32805
#define ID_STYLE_LEFT                   33000
#define ID_STYLE_CENTERED               33001
#define ID_STYLE_RIGHT                  33002
#define ID_STYLE_JUSTIFIED              33003
#define ID_PANEBAR                   59396
#define IDS_SELECTED_PROMPT             61208

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         34005
#define _APS_NEXT_CONTROL_VALUE         105
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
