//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UIThread.rc
//
#define IDR_UITHREAD                    128
#define ID_SPEED_SLOW                   32771
#define ID_SPEED_NORMAL                 32772
#define ID_SPEED_FAST                   32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
